version: 2.1
orbs:
  node: circleci/node@3.0.0
  cypress: cypress-io/cypress@1
  heroku: circleci/heroku@0.0.10
jobs:
  build-dev:
    docker: 
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: curl -X POST -d {} ${hookDEV} # run the `echo` command
  build-prod:
    docker: 
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: curl -X POST -d {} ${hook} # run the `echo` command
  # deploy-site:
  #   docker: 
  #     - image: cimg/node:14.10.1
  #   steps:
  #     - checkout
  #     - run:
  #       name: Deploy
  #       command: curl -X POST -d {} ${hook}
workflows:
  deployment-workflow:
    jobs:
      - cypress/run:
          start: 'npm run cypress:open'
      - build-prod:
          filter:
              branches:
                  only: master
      - build-dev:
          filter:
              branches:
                  only: /release\/*
      - heroku/deploy-via-git:
          app-name: ${HEROKU_APP_NAME}
          filter:
              branches:
                  only: master
      - heroku/deploy-via-git:
          app-name: ${HEROKU_APP_NAME_DEV}
          filter:
              branches:
                  only: /release\/*
            