describe("Form test", () => {
    it("Can fill the form", () => {
        cy.visit('localhost:3000')
        cy.get('input[id=userText]')
        .type("topicossw2020@gmail.com")
        cy.get('input[id=passwordText]')
        .type("topicos_2020")
        cy.get('Button[type=Submit').click()
        cy.wait(3000)
        cy.visit('localhost:3000/election')
        cy.wait(3000)
        cy.get('input[name="nameEl"]')
        .type("election_test")
        cy.get('input[name="startDate"]')
        .type("2020-12-28")
        cy.get('input[name="startDateHr"]')
        .type("09:00")
        cy.get('input[name="endDate"]')
        .type("2021-01-28")
        cy.get('input[name="endDateHr"]')
        .type("09:00")
        cy.get('input[name="minAge"]')
        .type("20")
        cy.get('input[name="maxAge"]')
        .type("30")
        cy.get('input[name="city"]')
        .type("Montevideo")
        cy.get('input[name="department"]')
        .type("Uruguay")
        cy.get('input[name="proposalName"]')
        .type("TestProposal")
        cy.get('input[name="proposalDescription"]')
        .type("TestPropDescription")
        cy.get('input[placeholder="Opcion 0"]')
        .type("TestOptionOne")
        cy.get('Button[name="addOption"]').click()
        cy.get('input[placeholder="Opcion 1"]')
        .type("TestOptionTwo")
        cy.get('Button[name="submitElection"]').click()
        cy.on('window:alert',(txt)=>{
            should('Creada correctamente')
        })
        
    });
});

